/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controlador.controlador;
import Modelo.Exportacion;
import Modelo.Metodos;
import Modelo.usuario;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis Felipe Usma C
 */
public class ExportacionVista extends javax.swing.JFrame {

    /**
     * Creates new form Exportancion
     */
    public ExportacionVista() {
        initComponents();
    this.setTitle("Exportaciones ");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelExportacion = new javax.swing.JPanel();
        TxtId = new javax.swing.JTextField();
        TxtNombreFunci = new javax.swing.JTextField();
        JblInfoFuncionario = new javax.swing.JLabel();
        TxtNombreP = new javax.swing.JTextField();
        TxtCantidad = new javax.swing.JTextField();
        JblInfoEmpleado = new javax.swing.JLabel();
        TxtNombreEmp = new javax.swing.JTextField();
        TxtPresentacionProducto = new javax.swing.JComboBox<>();
        TxtPaises = new javax.swing.JComboBox<>();
        TxtEnvio = new javax.swing.JComboBox<>();
        TxtCiudadDestino = new javax.swing.JTextField();
        TxtCuidadOrigen = new javax.swing.JTextField();
        TxtMonedaPago = new javax.swing.JComboBox<>();
        JblIDimportacion = new javax.swing.JLabel();
        BtnGuardar = new javax.swing.JButton();
        BtnListar = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnEiminar = new javax.swing.JButton();
        BtnActualizar = new javax.swing.JButton();
        Btnsalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnLimpiarF = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        PanelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelExportacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Importación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        PanelExportacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtId.setEditable(false);
        PanelExportacion.add(TxtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 24, 103, -1));

        TxtNombreFunci.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre completo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        TxtNombreFunci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreFunciActionPerformed(evt);
            }
        });
        PanelExportacion.add(TxtNombreFunci, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 250, -1));

        JblInfoFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JblInfoFuncionario.setText("Funcionario que recibe la exportación");
        JblInfoFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información del", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        PanelExportacion.add(JblInfoFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 286, 59));

        TxtNombreP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre del producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        PanelExportacion.add(TxtNombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 60, 177, 60));

        TxtCantidad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cantidad del producto (Kilos)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        PanelExportacion.add(TxtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 130, 182, 60));

        JblInfoEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JblInfoEmpleado.setText("Empleado que realiza la exportación");
        JblInfoEmpleado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información  del", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        PanelExportacion.add(JblInfoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 278, 59));

        TxtNombreEmp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre completo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        TxtNombreEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreEmpActionPerformed(evt);
            }
        });
        PanelExportacion.add(TxtNombreEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 250, -1));

        TxtPresentacionProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TxtPresentacionProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Entera", "En polvo", "Granulada" }));
        TxtPresentacionProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Presentacion Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        PanelExportacion.add(TxtPresentacionProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 62, 160, 60));

        TxtPaises.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TxtPaises.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Italia", "Francia", "España", "Estados unidos", "Alemania" }));
        TxtPaises.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista Países de destino", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        PanelExportacion.add(TxtPaises, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 260, 160, 70));

        TxtEnvio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TxtEnvio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Marítimo", "Terrestre", "Aéreo" }));
        TxtEnvio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de envio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        PanelExportacion.add(TxtEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 160, 60));

        TxtCiudadDestino.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ciudad de destino", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        PanelExportacion.add(TxtCiudadDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 182, 60));

        TxtCuidadOrigen.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ciudad de origen en Colombia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        PanelExportacion.add(TxtCuidadOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 190, 182, 60));

        TxtMonedaPago.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TxtMonedaPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Euros", "Dólares", "Pesos" }));
        TxtMonedaPago.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Moneda  de pago", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        TxtMonedaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMonedaPagoActionPerformed(evt);
            }
        });
        PanelExportacion.add(TxtMonedaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 160, 60));

        JblIDimportacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JblIDimportacion.setText("ID importación");
        PanelExportacion.add(JblIDimportacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 24, -1, -1));

        BtnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });
        PanelExportacion.add(BtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 100, -1));

        BtnListar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnListar.setText("Listar");
        PanelExportacion.add(BtnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 100, -1));

        BtnEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnEditar.setText("Editar");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });
        PanelExportacion.add(BtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 100, -1));

        BtnEiminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnEiminar.setText("Eliminar");
        PanelExportacion.add(BtnEiminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 310, 100, -1));

        BtnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnActualizar.setText("Actualizar datos");
        PanelExportacion.add(BtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, -1, -1));

        Btnsalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btnsalir.setText("Cerrar Sesión");
        Btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnsalirActionPerformed(evt);
            }
        });
        PanelExportacion.add(Btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 120, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Img2 (Pequeño).jpg"))); // NOI18N
        PanelExportacion.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 20, 310, 380));

        BtnLimpiarF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnLimpiarF.setText("Limpiar formulario");
        BtnLimpiarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarFActionPerformed(evt);
            }
        });
        PanelExportacion.add(BtnLimpiarF, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 140, -1));

        txtBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        PanelExportacion.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 362, 330, 60));

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        PanelExportacion.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, -1));

        PanelTabla.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        PanelTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Exportación", "Nombre Producto", "Presentación Producto", "Cantidad (Kilos)", "Tipo envio", "Cuidad destino", "Cuidad origen", "Pais destino", "Modeda de pago", "Funcionario", "Empleado"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        PanelTabla.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 24, 1314, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTabla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelExportacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelExportacion, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(PanelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNombreFunciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreFunciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreFunciActionPerformed

    private void TxtNombreEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreEmpActionPerformed

    private void TxtMonedaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMonedaPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMonedaPagoActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnsalirActionPerformed

        
    }//GEN-LAST:event_BtnsalirActionPerformed

    private void BtnLimpiarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarFActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_BtnLimpiarFActionPerformed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExportacionVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExportacionVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExportacionVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExportacionVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        usuario user = new usuario();
        Login log = new Login();
        Registro reg = new Registro();
        ExportacionVista exv=new ExportacionVista();
        Exportacion ex=new Exportacion();
        DefaultTableModel modelo = new DefaultTableModel();
        Metodos met = new Metodos();
        
        controlador con = new controlador(log, reg, user, exv, ex, modelo, met);
        
        exv.setVisible(true);
        
        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExportacionVista().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnActualizar;
    public javax.swing.JButton BtnEditar;
    public javax.swing.JButton BtnEiminar;
    public javax.swing.JButton BtnGuardar;
    public javax.swing.JButton BtnLimpiarF;
    public javax.swing.JButton BtnListar;
    public javax.swing.JButton Btnsalir;
    public javax.swing.JLabel JblIDimportacion;
    public javax.swing.JLabel JblInfoEmpleado;
    public javax.swing.JLabel JblInfoFuncionario;
    public javax.swing.JPanel PanelExportacion;
    public javax.swing.JPanel PanelTabla;
    public javax.swing.JTextField TxtCantidad;
    public javax.swing.JTextField TxtCiudadDestino;
    public javax.swing.JTextField TxtCuidadOrigen;
    public javax.swing.JComboBox<String> TxtEnvio;
    public javax.swing.JTextField TxtId;
    public javax.swing.JComboBox<String> TxtMonedaPago;
    public javax.swing.JTextField TxtNombreEmp;
    public javax.swing.JTextField TxtNombreFunci;
    public javax.swing.JTextField TxtNombreP;
    public javax.swing.JComboBox<String> TxtPaises;
    public javax.swing.JComboBox<String> TxtPresentacionProducto;
    public javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabla;
    public javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
