/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controlador.controlador;
import Modelo.Exportacion;
import Modelo.Metodos;
import Modelo.usuario;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis Felipe Usma C
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        //this.setTitle("iniciar sesión ");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        JblUsuario = new javax.swing.JLabel();
        JblContraseña = new javax.swing.JLabel();
        TxtUsuario = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        BtnRegistro = new javax.swing.JButton();
        TxtContrasena = new javax.swing.JPasswordField();
        BtnSalir = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JblUsuario.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        JblUsuario.setText("Usuario");
        Panel1.add(JblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 100, -1));

        JblContraseña.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        JblContraseña.setText("Contraseña");
        Panel1.add(JblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 100, -1));
        Panel1.add(TxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 120, -1));

        btnIngresar.setText("Ingresar");
        Panel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 100, -1));

        BtnRegistro.setText("Registrate");
        Panel1.add(BtnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 100, -1));
        Panel1.add(TxtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 120, -1));

        BtnSalir.setText("Salir");
        Panel1.add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 100, -1));
        BtnSalir.getAccessibleContext().setAccessibleName("Salir");

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Img3 (Pequeño).jpg"))); // NOI18N
        Panel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        usuario user = new usuario();
        Login log = new Login();
        Registro reg = new Registro();
        ExportacionVista exv=new ExportacionVista();
        Exportacion ex=new Exportacion();
        DefaultTableModel modelo = new DefaultTableModel();
        Metodos met = new Metodos();
        
        controlador con = new controlador(log, reg, user, exv, ex, modelo, met);
        con.iniciar();
       //log.setVisible(true);
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnRegistro;
    public javax.swing.JButton BtnSalir;
    public javax.swing.JLabel Fondo;
    private javax.swing.JLabel JblContraseña;
    private javax.swing.JLabel JblUsuario;
    public javax.swing.JPanel Panel1;
    public javax.swing.JPasswordField TxtContrasena;
    public javax.swing.JTextField TxtUsuario;
    public javax.swing.JButton btnIngresar;
    // End of variables declaration//GEN-END:variables
}
